# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/f/PycharmProjects/WeatherAPI/OpenWeatherUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(257, 742)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lcd0 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd0.setDigitCount(17)
        self.lcd0.setObjectName("lcd0")
        self.verticalLayout.addWidget(self.lcd0)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.weatherIcon = QtWidgets.QLabel(self.centralwidget)
        self.weatherIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.weatherIcon.setObjectName("weatherIcon")
        self.horizontalLayout_6.addWidget(self.weatherIcon)
        self.weatherLabel = QtWidgets.QLabel(self.centralwidget)
        self.weatherLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.weatherLabel.setMouseTracking(False)
        self.weatherLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weatherLabel.setObjectName("weatherLabel")
        self.horizontalLayout_6.addWidget(self.weatherLabel)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.waterIcon = QtWidgets.QLabel(self.centralwidget)
        self.waterIcon.setText("")
        self.waterIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.waterIcon.setObjectName("waterIcon")
        self.horizontalLayout_7.addWidget(self.waterIcon)
        self.waterTemp = QtWidgets.QLabel(self.centralwidget)
        self.waterTemp.setText("")
        self.waterTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.waterTemp.setObjectName("waterTemp")
        self.horizontalLayout_7.addWidget(self.waterTemp)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.lcd1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd1.setDigitCount(7)
        self.lcd1.setObjectName("lcd1")
        self.verticalLayout.addWidget(self.lcd1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lcd2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd2.setDigitCount(6)
        self.lcd2.setObjectName("lcd2")
        self.horizontalLayout.addWidget(self.lcd2)
        self.lcd3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd3.setDigitCount(6)
        self.lcd3.setObjectName("lcd3")
        self.horizontalLayout.addWidget(self.lcd3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lcd4 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd4.setObjectName("lcd4")
        self.horizontalLayout_4.addWidget(self.lcd4)
        self.lcd5 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd5.setObjectName("lcd5")
        self.horizontalLayout_4.addWidget(self.lcd5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.gridLayout_1 = QtWidgets.QGridLayout()
        self.gridLayout_1.setObjectName("gridLayout_1")
        self.forecastIcon3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forecastIcon3.sizePolicy().hasHeightForWidth())
        self.forecastIcon3.setSizePolicy(sizePolicy)
        self.forecastIcon3.setMinimumSize(QtCore.QSize(16, 16))
        self.forecastIcon3.setMaximumSize(QtCore.QSize(200, 16))
        self.forecastIcon3.setBaseSize(QtCore.QSize(0, 0))
        self.forecastIcon3.setText("")
        self.forecastIcon3.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastIcon3.setObjectName("forecastIcon3")
        self.gridLayout_1.addWidget(self.forecastIcon3, 1, 2, 1, 1)
        self.forecastTemp5 = QtWidgets.QLabel(self.centralwidget)
        self.forecastTemp5.setText("")
        self.forecastTemp5.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastTemp5.setObjectName("forecastTemp5")
        self.gridLayout_1.addWidget(self.forecastTemp5, 2, 4, 1, 1)
        self.forecastIcon1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forecastIcon1.sizePolicy().hasHeightForWidth())
        self.forecastIcon1.setSizePolicy(sizePolicy)
        self.forecastIcon1.setMinimumSize(QtCore.QSize(16, 16))
        self.forecastIcon1.setMaximumSize(QtCore.QSize(200, 16))
        self.forecastIcon1.setBaseSize(QtCore.QSize(0, 0))
        self.forecastIcon1.setText("")
        self.forecastIcon1.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastIcon1.setObjectName("forecastIcon1")
        self.gridLayout_1.addWidget(self.forecastIcon1, 1, 0, 1, 1)
        self.forecastTime3 = QtWidgets.QLabel(self.centralwidget)
        self.forecastTime3.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastTime3.setObjectName("forecastTime3")
        self.gridLayout_1.addWidget(self.forecastTime3, 0, 2, 1, 1)
        self.forecastIcon5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forecastIcon5.sizePolicy().hasHeightForWidth())
        self.forecastIcon5.setSizePolicy(sizePolicy)
        self.forecastIcon5.setMinimumSize(QtCore.QSize(16, 16))
        self.forecastIcon5.setMaximumSize(QtCore.QSize(200, 16))
        self.forecastIcon5.setBaseSize(QtCore.QSize(0, 0))
        self.forecastIcon5.setText("")
        self.forecastIcon5.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastIcon5.setObjectName("forecastIcon5")
        self.gridLayout_1.addWidget(self.forecastIcon5, 1, 4, 1, 1)
        self.forecastTemp3 = QtWidgets.QLabel(self.centralwidget)
        self.forecastTemp3.setText("")
        self.forecastTemp3.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastTemp3.setObjectName("forecastTemp3")
        self.gridLayout_1.addWidget(self.forecastTemp3, 2, 2, 1, 1)
        self.forecastTime2 = QtWidgets.QLabel(self.centralwidget)
        self.forecastTime2.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastTime2.setObjectName("forecastTime2")
        self.gridLayout_1.addWidget(self.forecastTime2, 0, 1, 1, 1)
        self.forecastTime4 = QtWidgets.QLabel(self.centralwidget)
        self.forecastTime4.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastTime4.setObjectName("forecastTime4")
        self.gridLayout_1.addWidget(self.forecastTime4, 0, 3, 1, 1)
        self.forecastTemp1 = QtWidgets.QLabel(self.centralwidget)
        self.forecastTemp1.setText("")
        self.forecastTemp1.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastTemp1.setObjectName("forecastTemp1")
        self.gridLayout_1.addWidget(self.forecastTemp1, 2, 0, 1, 1)
        self.forecastTemp4 = QtWidgets.QLabel(self.centralwidget)
        self.forecastTemp4.setText("")
        self.forecastTemp4.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastTemp4.setObjectName("forecastTemp4")
        self.gridLayout_1.addWidget(self.forecastTemp4, 2, 3, 1, 1)
        self.forecastTime1 = QtWidgets.QLabel(self.centralwidget)
        self.forecastTime1.setEnabled(True)
        self.forecastTime1.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastTime1.setObjectName("forecastTime1")
        self.gridLayout_1.addWidget(self.forecastTime1, 0, 0, 1, 1)
        self.forecastIcon4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forecastIcon4.sizePolicy().hasHeightForWidth())
        self.forecastIcon4.setSizePolicy(sizePolicy)
        self.forecastIcon4.setMinimumSize(QtCore.QSize(16, 16))
        self.forecastIcon4.setMaximumSize(QtCore.QSize(200, 16))
        self.forecastIcon4.setBaseSize(QtCore.QSize(0, 0))
        self.forecastIcon4.setText("")
        self.forecastIcon4.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastIcon4.setObjectName("forecastIcon4")
        self.gridLayout_1.addWidget(self.forecastIcon4, 1, 3, 1, 1)
        self.forecastIcon2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forecastIcon2.sizePolicy().hasHeightForWidth())
        self.forecastIcon2.setSizePolicy(sizePolicy)
        self.forecastIcon2.setMinimumSize(QtCore.QSize(16, 16))
        self.forecastIcon2.setMaximumSize(QtCore.QSize(200, 16))
        self.forecastIcon2.setBaseSize(QtCore.QSize(0, 0))
        self.forecastIcon2.setText("")
        self.forecastIcon2.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastIcon2.setObjectName("forecastIcon2")
        self.gridLayout_1.addWidget(self.forecastIcon2, 1, 1, 1, 1)
        self.forecastTemp2 = QtWidgets.QLabel(self.centralwidget)
        self.forecastTemp2.setText("")
        self.forecastTemp2.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastTemp2.setObjectName("forecastTemp2")
        self.gridLayout_1.addWidget(self.forecastTemp2, 2, 1, 1, 1)
        self.forecastTime5 = QtWidgets.QLabel(self.centralwidget)
        self.forecastTime5.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastTime5.setObjectName("forecastTime5")
        self.gridLayout_1.addWidget(self.forecastTime5, 0, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.forecastIcon1_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forecastIcon1_2.sizePolicy().hasHeightForWidth())
        self.forecastIcon1_2.setSizePolicy(sizePolicy)
        self.forecastIcon1_2.setMinimumSize(QtCore.QSize(16, 16))
        self.forecastIcon1_2.setMaximumSize(QtCore.QSize(200, 16))
        self.forecastIcon1_2.setBaseSize(QtCore.QSize(0, 0))
        self.forecastIcon1_2.setText("")
        self.forecastIcon1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastIcon1_2.setObjectName("forecastIcon1_2")
        self.gridLayout_2.addWidget(self.forecastIcon1_2, 1, 0, 1, 1)
        self.forecastTime2_2 = QtWidgets.QLabel(self.centralwidget)
        self.forecastTime2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastTime2_2.setObjectName("forecastTime2_2")
        self.gridLayout_2.addWidget(self.forecastTime2_2, 0, 1, 1, 1)
        self.forecastTemp3_2 = QtWidgets.QLabel(self.centralwidget)
        self.forecastTemp3_2.setText("")
        self.forecastTemp3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastTemp3_2.setObjectName("forecastTemp3_2")
        self.gridLayout_2.addWidget(self.forecastTemp3_2, 2, 2, 1, 1)
        self.forecastTemp1_2 = QtWidgets.QLabel(self.centralwidget)
        self.forecastTemp1_2.setText("")
        self.forecastTemp1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastTemp1_2.setObjectName("forecastTemp1_2")
        self.gridLayout_2.addWidget(self.forecastTemp1_2, 2, 0, 1, 1)
        self.forecastIcon2_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forecastIcon2_2.sizePolicy().hasHeightForWidth())
        self.forecastIcon2_2.setSizePolicy(sizePolicy)
        self.forecastIcon2_2.setMinimumSize(QtCore.QSize(16, 16))
        self.forecastIcon2_2.setMaximumSize(QtCore.QSize(200, 16))
        self.forecastIcon2_2.setBaseSize(QtCore.QSize(0, 0))
        self.forecastIcon2_2.setText("")
        self.forecastIcon2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastIcon2_2.setObjectName("forecastIcon2_2")
        self.gridLayout_2.addWidget(self.forecastIcon2_2, 1, 1, 1, 1)
        self.forecastIcon3_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forecastIcon3_2.sizePolicy().hasHeightForWidth())
        self.forecastIcon3_2.setSizePolicy(sizePolicy)
        self.forecastIcon3_2.setMinimumSize(QtCore.QSize(16, 16))
        self.forecastIcon3_2.setMaximumSize(QtCore.QSize(200, 16))
        self.forecastIcon3_2.setBaseSize(QtCore.QSize(0, 0))
        self.forecastIcon3_2.setText("")
        self.forecastIcon3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastIcon3_2.setObjectName("forecastIcon3_2")
        self.gridLayout_2.addWidget(self.forecastIcon3_2, 1, 2, 1, 1)
        self.forecastTemp2_2 = QtWidgets.QLabel(self.centralwidget)
        self.forecastTemp2_2.setText("")
        self.forecastTemp2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastTemp2_2.setObjectName("forecastTemp2_2")
        self.gridLayout_2.addWidget(self.forecastTemp2_2, 2, 1, 1, 1)
        self.forecastTime1_2 = QtWidgets.QLabel(self.centralwidget)
        self.forecastTime1_2.setEnabled(True)
        self.forecastTime1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastTime1_2.setObjectName("forecastTime1_2")
        self.gridLayout_2.addWidget(self.forecastTime1_2, 0, 0, 1, 1)
        self.forecastTime3_2 = QtWidgets.QLabel(self.centralwidget)
        self.forecastTime3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.forecastTime3_2.setObjectName("forecastTime3_2")
        self.gridLayout_2.addWidget(self.forecastTime3_2, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_5.addWidget(self.comboBox)
        self.updateButton = QtWidgets.QPushButton(self.centralwidget)
        self.updateButton.setObjectName("updateButton")
        self.horizontalLayout_5.addWidget(self.updateButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setObjectName("exitButton")
        self.verticalLayout.addWidget(self.exitButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "LOCATION"))
        self.weatherIcon.setText(_translate("MainWindow", "icon"))
        self.weatherLabel.setText(_translate("MainWindow", "condition"))
        self.label_2.setText(_translate("MainWindow", "Min"))
        self.label_3.setText(_translate("MainWindow", "Max"))
        self.label_4.setText(_translate("MainWindow", "Hum"))
        self.label_5.setText(_translate("MainWindow", "Pressure"))
        self.label_6.setText(_translate("MainWindow", "Preview"))
        self.forecastTime3.setText(_translate("MainWindow", "+9h"))
        self.forecastTime2.setText(_translate("MainWindow", "+6h"))
        self.forecastTime4.setText(_translate("MainWindow", "+12h"))
        self.forecastTime1.setText(_translate("MainWindow", "+3h"))
        self.forecastTime5.setText(_translate("MainWindow", "+15h"))
        self.label_7.setText(_translate("MainWindow", "Forecast"))
        self.forecastTime2_2.setText(_translate("MainWindow", "Today +1"))
        self.forecastTime1_2.setText(_translate("MainWindow", "Today"))
        self.forecastTime3_2.setText(_translate("MainWindow", "Today +2"))
        self.updateButton.setText(_translate("MainWindow", "Update"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))

